### ISSUE TITLE
How to check for errors?

### ISSUE THREAD

**Issue by andre-luiz-dos-santos** [jda/routeros-api-go#4]
What's the proper way to check for errors coming from the RouterOS device when using the Query() function?
I'm currently using the following code, which is what [the Connect() function uses to check for login errors](https://github.com/Netwurx/routeros-api-go/blob/f4957fb4129b538555281c808705830a294fc67c/api.go#L147). But shouldn't the Query() function return an error when it receives a !trap from the RouterOS device?

[get_routeros_interface_stats.go](https://gist.github.com/andre-luiz-dos-santos/e509cab2ab7412020f6b467797260d8d)
```go
if len(reply.Pairs) > 0 {
  log.Fatalf("RouterOS error: %+v", reply)
}
```

**Comment by jda** [comment]
Login errors are a bit of a special case where any unexpected output is assumed to be a error.

I added err response on !trap in bf5c969fa5acfcf0e705c1c0e3a74e7355f05963 but appears to be useful only in three situations:

1. Call() with an invalid command name: RouterOS will throw an error on an invalid command name ("/interface/explode")
2. Call() with invalid parameters: RouterOS will throw an error on an invalid parameter ("interface=badbridge")
3. Query() with an invalid command name:
RouterOS appears to only throw an error on an invalid command name. Invalid query parameters are silently ignored.

If I'm understanding your example, I'm not sure that is a case where RouterOS would send a !trap in reply to a "/interface/print". 
If you consider not getting any results from "/interface/print" to be an error, I'd do something like:
```go
if len(reply.Pairs) == 0 {
  log.Fatal("error: no interfaces")
}
```

Does that help?

**Comment by andre-luiz-dos-santos** [comment]
Thank you for the change. It's working as expected now.

I was fearful that I could be showing no interfaces because of an error, and not showing anything indicating that an error had happened.
The documentation is not very specific about what conditions could result in an error, specially category 4: http://wiki.mikrotik.com/wiki/Manual:API#.21trap
